---
title: Study Group Recommender with Machine Learning
subtitle: "Developed: by class of DATA322 Presented: by Team Machines"
execute:
   error: true
jupyter: python3
format: pptx
---
```{python}
#| echo: false

import qrcode
import matplotlib.pyplot as plt
```

# Problem Overview
Many students struggle with understanding course material, staying accountable, and performing well on exams. While study groups can feel intimidating, research shows they significantly improve comprehension, retention, and exam scores. Now the big question is: How do we create effective study groups that maximize learning, accountability, and confidence while minimizing the fear of participation?


# Data Collection - Fill Out This Form!
First, please fill out our short survey, which we’ll use to recommend everyone’s study groups! While you are all filling that out, we’ll begin talking about the methods used in our hierarchical clustering algorithm. You are all your own cluster to start, but will begin merging together one by one based on similarity and differences in responses!

```{python}
url="https://docs.google.com/forms/d/e/1FAIpQLSdO8crqtnLQZqj-13miPjY7mofl3iHILaMsBXpKWxbkXv0R2w/viewform"
# Create QR code

qr=qrcode.QRCode(version=None, box_size=8, border=4)
qr.add_data(url)
qr.make(fit=True)
img = qrcode.make(url).convert("RGB") 
#img=qr.make_image(fill_color="black", back_color="white")
# Display QR code
plt.imshow(img)
plt.axis("off")
plt.show()
```

# Tidy Data Collected 

# Distance Definition

# How distance between students work?

# Clustering: Linkage Choice

# Clustering: Code and Dendrogram

# Group Recommendations and Student Assignment

# Evaluation Form (from Presenting Team)
- Link: [https://forms.gle/mBq7GdZiLTy8Ydhf9](https://forms.gle/mBq7GdZiLTy8Ydhf9)
```{python}
url="https://forms.gle/mBq7GdZiLTy8Ydhf9"
# Create QR code

qr=qrcode.QRCode(version=None, box_size=10, border=4)
qr.add_data(url)
qr.make(fit=True)
img = qrcode.make(url).convert("RGB") 
#img=qr.make_image(fill_color="black", back_color="white")
# Display QR code
plt.imshow(img)
plt.axis("off")
plt.show()
```


# Credits
- Presented by Team Machines:
    - Anthony Wolfe - Project Coordinator
    - Dean Callahan - Technical Lead
    - Jonathan Juarez - Data Scientist
    - Devon Walker - Data Scientist

- Data and Question Design By: Team SARA
- Distance and Clustering By: Team Errors
